version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
  client:
    depends_on: 
      - server
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"